# Generated by Django 3.0.5 on 2022-12-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('account_owner', models.CharField(max_length=90)),
                ('account_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Account_status')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=99)),
                ('contact_cidn', models.IntegerField()),
                ('contact_price', models.FloatField()),
                ('contact_phone', models.IntegerField()),
                ('contact_email', models.EmailField(max_length=99)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Accounts')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Industry'),
        ),
    ]
